### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by chiz0me** [FlameOfIgnis/github-year-draw#1]
Traceback (most recent call last):
  File "github-draw.py", line 19, in <module>
    im = Image.open(str(sys.argv[1])) #convert monochrome bpm to bool array
IndexError: list index out of range

**Comment by ignis-sec** [comment]
Hello, did you run it with a command line arguement supplying a monochrome bitmap? If not, you need to pass it an arguement and i havent caught any of the possible errors properly yet. 
If you did pass an arguement, can you share which image it was?

**Comment by ignis-sec** [comment]
Im assuming you didn't pass a console arguement, and closing this issue.
